#!/usr/bin/env python3
"""
image-to-pov.py — Convert PNG/JPG images to POV frame data for the Spirit Sphere

Converts an input image into a C header file containing column-ordered RGB data
suitable for loading into the POV globe frame buffer.

Supports two projection modes:
  - sphere (default): Equirectangular projection for spherical POV display.
    Input image is treated as longitude (x) x latitude (y), mapped to
    columns (angular positions) x LEDs (arm positions).
  - flat: Simple resize for flat/propeller-style POV displays.

Usage Examples:
  # Basic equirectangular sphere conversion
  python scripts/image-to-pov.py earth.png -o firmware/pov-globe/image_data.h

  # Flat mode with custom resolution
  python scripts/image-to-pov.py logo.png --mode flat --columns 60 --leds 24 -o output.h

  # Generate preview image to check before flashing
  python scripts/image-to-pov.py earth.png --preview -o firmware/pov-globe/image_data.h

  # Adjust gamma and pre-dim for low-light use
  python scripts/image-to-pov.py art.png --gamma 2.0 --brightness 0.5 -o output.h

Requirements: pip install Pillow numpy
"""

import sys
import os
import argparse
import math

# Dependency check with helpful error
try:
    from PIL import Image
    import numpy as np
except ImportError:
    print("Missing dependencies. Install with:")
    print("  pip install Pillow numpy")
    sys.exit(1)

# Default values matching firmware/pov-globe/config.h
DEFAULT_COLUMNS = 120
DEFAULT_LEDS = 36
DEFAULT_GAMMA = 2.2
DEFAULT_BRIGHTNESS = 1.0


def apply_gamma(pixel_array: np.ndarray, gamma: float) -> np.ndarray:
    """Apply gamma correction for LED brightness perception.

    LEDs have linear brightness output but human perception is non-linear.
    Gamma correction (typically 2.2) makes brightness appear more natural.
    """
    # Normalize to 0-1, apply gamma, scale back to 0-255
    normalized = pixel_array.astype(np.float64) / 255.0
    corrected = np.power(normalized, gamma)
    return (corrected * 255.0).clip(0, 255).astype(np.uint8)


def apply_brightness(pixel_array: np.ndarray, brightness: float) -> np.ndarray:
    """Apply brightness multiplier (0.0 to 1.0) for pre-dimming."""
    if brightness >= 1.0:
        return pixel_array
    scaled = pixel_array.astype(np.float64) * brightness
    return scaled.clip(0, 255).astype(np.uint8)


def convert_sphere(img: Image.Image, num_columns: int, num_leds: int) -> np.ndarray:
    """Convert equirectangular image to POV column data (sphere mode).

    The input image is an equirectangular projection (like a world map):
      - X axis = longitude (0 to 360 degrees)
      - Y axis = latitude (pole to pole)

    For each angular column position, sample a vertical strip from the
    image at the corresponding longitude and resample to num_leds pixels.

    Returns: numpy array of shape (num_columns, num_leds, 3) in RGB.
    """
    # Resize image: width = num_columns (longitude samples), height = num_leds (latitude)
    # This is the correct mapping for equirectangular -> POV sphere:
    # each column in the resized image is one angular position,
    # each row is one LED position along the arm.
    resized = img.resize((num_columns, num_leds), Image.Resampling.LANCZOS)
    arr = np.array(resized)

    # Result shape: [columns, leds, 3]
    # Transpose from (height, width, 3) to (width, height, 3) = (columns, leds, 3)
    return arr.transpose(1, 0, 2)


def convert_flat(img: Image.Image, num_columns: int, num_leds: int) -> np.ndarray:
    """Convert image to POV column data (flat/propeller mode).

    Simple resize: image width maps to columns (left-to-right = angular sweep),
    image height maps to LEDs (top-to-bottom = center-to-edge on propeller arm).

    Returns: numpy array of shape (num_columns, num_leds, 3) in RGB.
    """
    resized = img.resize((num_columns, num_leds), Image.Resampling.LANCZOS)
    arr = np.array(resized)
    return arr.transpose(1, 0, 2)


def generate_c_header(frame_data: np.ndarray, source_filename: str,
                      num_columns: int, num_leds: int) -> str:
    """Generate a C header file with PROGMEM uint8_t array.

    Data format: sequential columns, each column is num_leds x 3 bytes (R, G, B).
    Compatible with frame_load() in firmware/pov-globe/frame_buffer.cpp.
    """
    lines = []
    lines.append(f"// Generated by image-to-pov.py from {source_filename}")
    lines.append(f"// {num_columns} columns x {num_leds} LEDs x 3 bytes (RGB)")
    lines.append(f"// Total: {num_columns * num_leds * 3} bytes")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("const uint8_t FRAME_DATA[] PROGMEM = {")

    for col in range(num_columns):
        lines.append(f"    // Column {col}")
        col_bytes = []
        for led in range(num_leds):
            r, g, b = frame_data[col, led]
            col_bytes.append(f"    0x{r:02X}, 0x{g:02X}, 0x{b:02X},  // LED {led}")
        lines.extend(col_bytes)

    lines.append("};")
    lines.append("")
    lines.append("const size_t FRAME_DATA_LEN = sizeof(FRAME_DATA);")
    lines.append("")

    return "\n".join(lines)


def save_preview(frame_data: np.ndarray, output_path: str,
                 num_columns: int, num_leds: int) -> str:
    """Save a preview PNG visualizing the frame buffer.

    The preview shows columns as vertical strips: num_columns wide x num_leds tall.
    This matches what the POV display will render (unrolled from sphere to flat).
    """
    # frame_data is (columns, leds, 3) -> transpose to (leds, columns, 3) for image
    preview_arr = frame_data.transpose(1, 0, 2)
    preview_img = Image.fromarray(preview_arr, mode="RGB")

    # Scale up for visibility (at least 4x)
    scale = max(4, 800 // max(num_columns, num_leds))
    preview_img = preview_img.resize(
        (num_columns * scale, num_leds * scale),
        Image.Resampling.NEAREST
    )

    # Derive preview path from output path
    base, ext = os.path.splitext(output_path)
    preview_path = f"{base}_preview.png"
    preview_img.save(preview_path)
    return preview_path


def main():
    parser = argparse.ArgumentParser(
        description="Convert PNG/JPG images to POV frame data for the Spirit Sphere",
        epilog="Output is a C header file loadable by frame_load() in the POV globe firmware."
    )
    parser.add_argument("input", help="Input image file (PNG, JPG, etc.)")
    parser.add_argument("-o", "--output", required=True,
                        help="Output C header file path")
    parser.add_argument("--mode", choices=["flat", "sphere"], default="sphere",
                        help="Projection mode (default: sphere)")
    parser.add_argument("--columns", type=int, default=DEFAULT_COLUMNS,
                        help=f"Number of angular columns (default: {DEFAULT_COLUMNS})")
    parser.add_argument("--leds", type=int, default=DEFAULT_LEDS,
                        help=f"Number of LEDs per arm (default: {DEFAULT_LEDS})")
    parser.add_argument("--gamma", type=float, default=DEFAULT_GAMMA,
                        help=f"Gamma correction value (default: {DEFAULT_GAMMA})")
    parser.add_argument("--brightness", type=float, default=DEFAULT_BRIGHTNESS,
                        help="Brightness multiplier 0.0-1.0 (default: 1.0)")
    parser.add_argument("--preview", action="store_true",
                        help="Save a preview PNG showing the POV frame buffer")

    args = parser.parse_args()

    # Validate input
    if not os.path.isfile(args.input):
        print(f"Error: Input file not found: {args.input}")
        sys.exit(1)

    if args.brightness < 0.0 or args.brightness > 1.0:
        print("Error: --brightness must be between 0.0 and 1.0")
        sys.exit(1)

    # Load image
    print(f"Loading: {args.input}")
    img = Image.open(args.input).convert("RGB")
    print(f"  Size: {img.width}x{img.height}")

    # Convert based on mode
    print(f"  Mode: {args.mode}")
    print(f"  Target: {args.columns} columns x {args.leds} LEDs")

    if args.mode == "sphere":
        frame_data = convert_sphere(img, args.columns, args.leds)
    else:
        frame_data = convert_flat(img, args.columns, args.leds)

    # Apply brightness (before gamma)
    if args.brightness < 1.0:
        print(f"  Brightness: {args.brightness:.2f}")
        frame_data = apply_brightness(frame_data, args.brightness)

    # Apply gamma correction
    print(f"  Gamma: {args.gamma}")
    frame_data = apply_gamma(frame_data, args.gamma)

    # Generate C header
    source_name = os.path.basename(args.input)
    header_content = generate_c_header(frame_data, source_name, args.columns, args.leds)

    # Write output
    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w") as f:
        f.write(header_content)

    total_bytes = args.columns * args.leds * 3
    print(f"  Output: {args.output} ({total_bytes} bytes of pixel data)")

    # Generate preview if requested
    if args.preview:
        preview_path = save_preview(frame_data, args.output, args.columns, args.leds)
        print(f"  Preview: {preview_path}")

    print("Done.")


if __name__ == "__main__":
    main()
