#!/usr/bin/env python3
"""
vault-moc-gen.py — Step 3/5: Generate per-theme Map-of-Content notes.

Usage: python3 vault-moc-gen.py [--vault PATH] [--dry-run]
Default vault: /Volumes/Extreme Pro/MIGRATION/2501-DEPLOYMENT/obsidian-vault
Exit 0 on success, non-zero on error.
Prints summary: "mocs_created: N / mocs_updated: M / mocs_unchanged: K"
"""

import argparse
import hashlib
import os
import re
import sys
from datetime import date

import frontmatter

VAULT_DEFAULT = "/Volumes/Extreme Pro/MIGRATION/2501-DEPLOYMENT/obsidian-vault"
SKIP_DIRS = {".obsidian", ".trash", ".git", "MOC"}
AUTO_END_MARKER = "<!-- end-auto -->"


def collect_md_files(vault):
    result = []
    for root, dirs, files in os.walk(vault):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in files:
            if f.endswith(".md") and not f.startswith("._"):
                result.append(os.path.join(root, f))
    return result


def get_note_tags(path):
    """Return list of tags from a note's YAML frontmatter."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            raw = f.read()
        post = frontmatter.loads(raw)
        tags = post.get("tags", [])
        if isinstance(tags, str):
            tags = [t.strip() for t in tags.split(",") if t.strip()]
        elif isinstance(tags, list):
            tags = [str(t) for t in tags]
        else:
            tags = []
        return tags
    except Exception:
        return []


def build_theme_map(md_files):
    """Return {theme: [note_stem, ...]} sorted alphabetically."""
    theme_map = {}
    for path in md_files:
        tags = get_note_tags(path)
        stem = os.path.splitext(os.path.basename(path))[0]
        for tag in tags:
            theme_map.setdefault(tag, [])
            if stem not in theme_map[tag]:
                theme_map[tag].append(stem)
    # Sort note lists alphabetically
    for theme in theme_map:
        theme_map[theme] = sorted(theme_map[theme])
    return theme_map


def make_moc_auto_section(theme, notes, iso_date):
    """Return the auto-generated portion of a MOC file (above end-auto marker)."""
    note_count = len(notes)
    lines = [
        "---",
        "moc: true",
        f"theme: {theme}",
        f"generated: {iso_date}",
        f"note_count: {note_count}",
        "---",
        "",
        f"# MOC: {theme.replace('-', ' ').title()}",
        "",
        f"> Auto-generated. Regenerated by `~/scripts/vault-moc-gen.py`. Do not hand-edit the list section.",
        "",
        f"## Notes ({note_count})",
        "",
    ]
    for stem in notes:
        lines.append(f"- [[{stem}]]")
    lines.append("")
    return "\n".join(lines)


def stable_hash(content):
    """SHA-256 of content string, used for change detection."""
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def write_moc(path, theme, notes, iso_date, dry_run):
    """
    Write or update a MOC file. Returns ('created'|'updated'|'unchanged').
    Preserves any hand-written content below <!-- end-auto --> marker.
    """
    auto_section = make_moc_auto_section(theme, notes, iso_date)
    # Strip the timestamp line for stable comparison
    auto_section_stable = re.sub(r'^generated: .*$', 'generated: STABLE', auto_section, flags=re.MULTILINE)

    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            existing = f.read()
        # Split on end-auto marker
        if AUTO_END_MARKER in existing:
            before_marker = existing.split(AUTO_END_MARKER)[0]
            after_marker = AUTO_END_MARKER + existing.split(AUTO_END_MARKER, 1)[1]
        else:
            before_marker = existing
            after_marker = "\n" + AUTO_END_MARKER + "\n"

        existing_stable = re.sub(r'^generated: .*$', 'generated: STABLE', before_marker, flags=re.MULTILINE)

        if stable_hash(existing_stable) == stable_hash(auto_section_stable):
            return "unchanged"

        new_content = auto_section + after_marker
        if not dry_run:
            with open(path, "w", encoding="utf-8") as f:
                f.write(new_content)
        return "updated"
    else:
        # New file
        new_content = auto_section + "\n" + AUTO_END_MARKER + "\n"
        if not dry_run:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(new_content)
        return "created"


def write_readme(moc_dir, themes, iso_date, dry_run):
    """Write MOC/README.md linking to all theme MOCs."""
    lines = [
        "---",
        "moc: true",
        f"generated: {iso_date}",
        "---",
        "",
        "# Map of Contents",
        "",
        "> Auto-generated index of all theme MOCs. Regenerated by `~/scripts/vault-moc-gen.py`.",
        "",
        "## Themes",
        "",
    ]
    for theme in sorted(themes):
        note_count = len(themes[theme])
        lines.append(f"- [[{theme}]] ({note_count} notes)")
    lines.append("")
    content = "\n".join(lines)

    readme_path = os.path.join(moc_dir, "README.md")
    # Stable comparison: strip timestamp
    content_stable = re.sub(r'^generated: .*$', 'generated: STABLE', content, flags=re.MULTILINE)

    if os.path.exists(readme_path):
        with open(readme_path, "r", encoding="utf-8") as f:
            existing = f.read()
        existing_stable = re.sub(r'^generated: .*$', 'generated: STABLE', existing, flags=re.MULTILINE)
        if stable_hash(content_stable) == stable_hash(existing_stable):
            return "unchanged"
        if not dry_run:
            with open(readme_path, "w", encoding="utf-8") as f:
                f.write(content)
        return "updated"
    else:
        if not dry_run:
            with open(readme_path, "w", encoding="utf-8") as f:
                f.write(content)
        return "created"


def main():
    parser = argparse.ArgumentParser(description="Generate per-theme MOC notes")
    parser.add_argument("--vault", default=VAULT_DEFAULT)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    vault = args.vault
    if not os.path.isdir(vault):
        print(f"ERROR: vault not found at {vault}", file=sys.stderr)
        sys.exit(1)

    moc_dir = os.path.join(vault, "MOC")
    if not args.dry_run:
        os.makedirs(moc_dir, exist_ok=True)

    md_files = collect_md_files(vault)
    theme_map = build_theme_map(md_files)
    iso_date = date.today().isoformat()

    created = updated = unchanged = 0

    for theme, notes in sorted(theme_map.items()):
        moc_path = os.path.join(moc_dir, f"{theme}.md")
        result = write_moc(moc_path, theme, notes, iso_date, args.dry_run)
        if result == "created":
            created += 1
        elif result == "updated":
            updated += 1
        else:
            unchanged += 1

    readme_result = write_readme(moc_dir, theme_map, iso_date, args.dry_run)
    if readme_result == "created":
        created += 1
    elif readme_result == "updated":
        updated += 1
    else:
        unchanged += 1

    mode = " [DRY-RUN]" if args.dry_run else ""
    print(f"mocs_created: {created} / mocs_updated: {updated} / mocs_unchanged: {unchanged}{mode}")


if __name__ == "__main__":
    main()
